### ISSUE TITLE
SudsLibrary 0.8 is not compatible with suds-jurko

### ISSUE THREAD

**Issue by ombre42** [ombre42/robotframework-sudslibrary#17]
The suds-jurko fork removed the UTC class. The code needs to be rewritten so as to not depend on it.

```
Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from SudsLibrary import SudsLibrary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\apps\Python27\lib\site-packages\SudsLibrary\__init__.py", line 23, in <module>
    from .wsse import _WsseKeywords
  File "C:\apps\Python27\lib\site-packages\SudsLibrary\wsse.py", line 21, in <module>
    from suds.sax.date import UTC
ImportError: cannot import name UTC
```

**Comment by ombre42** [comment]
have removed dependency on class deleted from Jurko, however there are some other failures specific to the jurko fork I am working on (returning xml instead of object graph).

**Comment by alisterdarrel** [comment]
Whats the solution for this error ?

20160827 00:26:03.254 [WARN]: Importing test library "SudsLibrary" failed

Traceback (most recent call last):
Importing test library 'SudsLibrary' failed: ImportError: cannot import name UTC
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 143, in _import
    return __import__(name, fromlist=fromlist)
  File "C:\Python27\lib\site-packages\SudsLibrary__init__.py", line 23, in <module>
    from .wsse import _WsseKeywords
  File "C:\Python27\lib\site-packages\SudsLibrary\wsse.py", line 21, in <module>
    from suds.sax.date import UTC
PYTHONPATH:
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\Scripts
  C:\WINDOWS\SYSTEM32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\robotide\spec
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 46, in TestLibrary
    return_source=True)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 67, in import_class_or_module
    self._raise_import_failed(name, err)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 103, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by roboki** [comment]
Any updates of this issue?
